# Generated by Django 4.0.5 on 2022-10-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=4000)),
                ('price', models.IntegerField(max_length=30)),
                ('img', models.ImageField(upload_to='productImg')),
            ],
        ),
    ]
