# Generated by Django 4.0.5 on 2022-10-23 22:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_cart_date_alter_contact_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('Date', models.DateField(default=datetime.datetime(2022, 10, 23, 23, 52, 48, 179878))),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 23, 52, 48, 177879)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 10, 23, 23, 52, 48, 179878)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 23, 52, 48, 176881)),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.AddField(
            model_name='productreview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
