# Generated by Django 4.0.5 on 2022-10-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productreview_alter_cart_date_alter_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tire_size',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 16, 10, 57, 582196)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 16, 10, 57, 583197)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 16, 10, 57, 580198)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 16, 10, 57, 584197)),
        ),
    ]
